---
title: Green Ruby News
description: A Newsletter dedicated to weekly fresh news about ruby, web development, javascript, and related topics.
keywords: "ruby, rails, newsletter, webdev, js, javascript, geeks, podcasts, devops, links"
contact_email: news@greenruby.or
base_url: http://greenruby.org
copyright: Mose
mailchimp_subscribe: "http://greenruby.us6.list-manage.com/subscribe/post?u=f1b3b59d2383eeb07537f6440&amp;id=7136c985cf"
social:
  - title: Github
    url: https://github.com/greenruby
  - title: Twitter
    url: http://twitter.com/greenrubist
  - title: Facebook
    url: https://www.facebook.com/pages/Green-Ruby/1413063455616628
